export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'

export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST'
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS'
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL'

export const CART_ITEMS_REQUEST = 'CART_ITEMS_REQUEST'
export const CART_ITEMS_SUCCESS = 'CART_ITEMS_SUCCESS'
export const CART_ITEMS_FAIL = 'CART_ITEMS_FAIL'
export const CART_ITEMS_RESET = 'CART_ITEMS_RESET'

