export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_MY_LIST_REQUEST = 'ORDER_MY_LIST_REQUEST'
export const ORDER_MY_LIST_SUCCESS = 'ORDER_MY_LIST_SUCCESS'
export const ORDER_MY_LIST_FAIL = 'ORDER_MY_LIST_FAIL'
export const ORDER_MY_LIST_RESET = 'ORDER_MY_LIST_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS'
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL'
